### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by AshxStudio** [mo1ein/TelegramArchive#1]
export channels that restrict saving content is my need,thanks ,but how to run?

**Comment by AshxStudio** [comment]
thks but how to  export channels that restrict saving content

**Comment by mo1ein** [comment]
Send channel post to bot. If channel is private, send join link.

**Comment by wordfangsss** [comment]
the bot is dead ? coz i've start it but no response from the bot

**Comment by mo1ein** [comment]
> the bot is dead ? coz i've start it but no response from the bot

Not actually. Now days I'm busy. Can you explain problem exactly?
